ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
ARDMK_PATH    = /usr/bin
AVR_TOOLS_DIR = /usr


BOARD_TAG = mega2560
MONITOR_PORT = /dev/ttyUSB0
MONITOR_BAUDRATE = 115200
ARDUINO_LIBS = 

include $(ARDMK_DIR)/Arduino.mk
